In [1]:
import pandas as pd

In [2]:
#Handle missing data

df=pd.read_csv("raw_data.csv")
df.isnull()
df.isna()
df.isnull().sum()
df.dropna() #row drop containing null values
df.dropna(axis=1) #column drop
mean_age=df["age"].mean()
df.fillna(100)
df.fillna(mean_age)
cleaned_data=df.copy()
mean_age=cleaned_data["age"].mean()
cleaned_data["age"]=cleaned_data["age"].fillna(mean_age)

#cleaned_data
df.ffill() #forward fill

df.bfill()  #backword fill

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
#handle duplicate data

df.duplicated()
df["country"].duplicated() #checking for one column
df[["country","name"]].duplicated() #checking duplicate values for a set of column
df2=df.copy()
df.drop_duplicates(inplace=True)

In [4]:
#Data types
df.dtypes
df2=df.copy()
df2 = df2.fillna(0)
df2["age"]=df2["age"].astype("int64")
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [5]:
#handle strings
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()
df["name"].str.split(" ")
df["country"].str.contains("Usa",case=False)

0      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object

In [6]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [7]:
aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"]= pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtypes

dtype('<M8[ns]')

In [8]:
data_str= pd.Series([pd.to_datetime("2026-12-01")])
type(data_str.dtypes)

numpy.dtypes.DateTime64DType