In [63]:
import pandas as pd

In [2]:
df=pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [28]:
#feature engineering
df2=df.copy()
#apply fnx
df2["tax"]=df2["income"].apply(lambda x:"20%"if x>=60000 else "10%" )

#map fnx
gender_map={"Male": "M", "Female": "F", "Unknown": "U"}
df2["gender"]=df2["gender"].map(gender_map)

#assign fnx
df2=df2.assign(new_income = df2["income"]*1.1)

#replace fnx
df2["country"]=df2["country"].replace("USA","US")

#rename
df2.rename(columns={"income":"Salary"}) #one particular column rename
df2.rename(index={1:"First"})

#sorting
df2.sort_values("income") 
#descending order
df2.sort_values("income", ascending = False) 

sorted_df=df2.sort_values(["income","age"])
sorted_df.sort_index()

#reset index
sorted_df.reset_index()
#if preserved index is not needed
sorted_df.reset_index(drop=True)

#ranking
sorted_df["Ranking"]=sorted_df["income"].rank()
sorted_df["Ranking"]=sorted_df["income"].rank(ascending=False,method="min")
sorted_df

    id          name   age country gender   income  tax  new_income  Ranking
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0     10.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0      9.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0      8.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0      6.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0      6.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0      5.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      3.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0      3.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0      2.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0      1.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN      NaN

In [13]:
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [32]:
df2=df.copy()
new_col_order=[col for col in df2.columns if col!="id"] +["id"]
df2[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [45]:
#cleaning the df for loading it into csv files
df2=df.copy()
df2=df2.drop_duplicates()
df2=df2.fillna(0)
df2=df2.sort_values("income")
df2=df2.reset_index(drop=True)
#loading this  df2 into csv file
df2.to_csv("sorted_data.csv")

In [44]:
df2

   id          name   age country   gender   income
0   4  Maria Garcia  34.0   Spain   Female      0.0
1   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2   3          Alex   0.0     USA  Unknown  47000.0
3   5        Li Wei  27.0   China     Male  51000.0
4   1      John Doe  29.0     USA     Male  55000.0
5  10   Emily Davis  31.0     USA        0  58000.0
6   2    Jane Smith   0.0  Canada   Female  62000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   7    Ahmed Khan  38.0       0     Male  68000.0
9   6             0  45.0   India   Female  73000.0

In [29]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0