In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("sorted_data.csv")

In [3]:
#melt and pivot data
df=pd.DataFrame({
    "Country":["USA","USA","India","India"],
    "Year":[2020,2021,2020,2021],
    "sales":[100,120,90,110],
    "profit":[20,25,18,22],
    "tax":[10,20,30,40]
})
melted_df=df.melt(
    id_vars=["Country","Year"],
    value_vars=["sales","profit","tax"],
    var_name="metrices",
    value_name="value"       
)

melted_df.pivot(
    index=["Country","Year"],
    columns="metrices",
    values="value"

)

metrices      profit  sales  tax
Country Year
India   2020      18     90   30
        2021      22    110   40
USA     2020      20    100   10
        2021      25    120   20

In [4]:
df

  Country  Year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   40